name = "Plumes"
uuid = "bad9e75c-82a8-4a1c-82f7-a87e1b719d4d"
authors = ["Sam Aucoin", "sam.aucoin@dal.ca"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
